version: '3'

services:
  web-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: taxi-voucher-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:8.1.0
    container_name: todo-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_PASSWORD: my-secret-pw
      MYSQL_DATABASE: todo_list
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
